
'use client';
//become SSG
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( //在這加上 navebar 所有page 皆會出現 //因為所有page share the same layout.tsx
    <html lang="en">
      <head><title>moi</title></head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
